language: go

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - if [ -n "$(gofmt -s -l . | grep -v "vendor")" ]; then diff -u <(echo -n) <(gofmt -d $(gofmt -s -l . | grep -v "vendor")); fi
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go get github.com/haya14busa/goverage
  - goverage -coverprofile=coverage.txt ./...
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: docker
      name: "Integration Tests"
      script:
        - docker build -t svalinn:local .
        - docker --version
        - docker-compose --version
        - docker swarm init
        - go get github.com/Comcast/codex
        # build gungnir
        - go get github.com/Comcast/codex-gungnir
        - cd ../codex-gungnir
        - docker build -t gungnir:local
        - cd ../codex/deploy/docker-compose
        - docker-compose up -d